import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "F",     mods = "Alt", action = "ToggleSimpleFullscreen" },
  { key = "Q",     mods = "Command",  action = "None" },
]

[window]
padding.x = 10
padding.y = 10
# dimensions.columns = 140
# dimensions.lines = 40

decorations = "Buttonless"
startup_mode = "Maximized"

# opacity = 0.8
# blur = true

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font Mono"
normal.style = "Light"
size = 16
